### ISSUE TITLE
miscService dependency error 

### ISSUE THREAD

**Issue by coderAlone** [DmitryEfimenko/FlowJs-MVC#4]
Upload.js the dependency miscService is giving an error do i need to inject something into the controller?

**Comment by DmitryEfimenko** [comment]
In my project the flow.js requests needed to be authenticated, which might not be your case. But event if it is, this piece of code depends on your project's authentication implementation, which is why I didn't include it in this project.

Mine was using Bearer authentication and the function under miscService looked like this:

``` javascript
function getSecurityHeaders(accessToken) {
    accessToken = accessToken || sessionStorage['accessToken'] || localStorage['accessToken'];

    if (accessToken) {
        return { 'Authorization': 'Bearer ' + accessToken };
    }

    return null;
};
```

It's up to you to handle your authentication appropriately.
